# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pdf_mark_create_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdf_mark_create_MainWindow(object):
    def setupUi(self, pdf_mark_create_MainWindow):
        pdf_mark_create_MainWindow.setObjectName("pdf_mark_create_MainWindow")
        pdf_mark_create_MainWindow.resize(699, 695)
        self.centralwidget = QtWidgets.QWidget(pdf_mark_create_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.content_tableWidget.setAlternatingRowColors(False)
        self.content_tableWidget.setObjectName("content_tableWidget")
        self.content_tableWidget.setColumnCount(0)
        self.content_tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.content_tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.open_file_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_pushButton.setObjectName("open_file_pushButton")
        self.horizontalLayout.addWidget(self.open_file_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pdf_path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_path_lineEdit.setObjectName("pdf_path_lineEdit")
        self.horizontalLayout_2.addWidget(self.pdf_path_lineEdit)
        self.pdf_open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pdf_open_pushButton.setObjectName("pdf_open_pushButton")
        self.horizontalLayout_2.addWidget(self.pdf_open_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.tolerance_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tolerance_lineEdit.setObjectName("tolerance_lineEdit")
        self.horizontalLayout_3.addWidget(self.tolerance_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.clear_table_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clear_table_pushButton.setObjectName("clear_table_pushButton")
        self.verticalLayout.addWidget(self.clear_table_pushButton)
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.verticalLayout.addWidget(self.start_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        pdf_mark_create_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pdf_mark_create_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        pdf_mark_create_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pdf_mark_create_MainWindow)
        self.statusbar.setObjectName("statusbar")
        pdf_mark_create_MainWindow.setStatusBar(self.statusbar)
        self.help_action = QtWidgets.QAction(pdf_mark_create_MainWindow)
        self.help_action.setObjectName("help_action")
        self.menuHelp.addAction(self.help_action)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(pdf_mark_create_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(pdf_mark_create_MainWindow)

    def retranslateUi(self, pdf_mark_create_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        pdf_mark_create_MainWindow.setWindowTitle(_translate("pdf_mark_create_MainWindow", "LW PDF add mark tool"))
        self.open_file_pushButton.setText(_translate("pdf_mark_create_MainWindow", "目录文件"))
        self.pdf_open_pushButton.setText(_translate("pdf_mark_create_MainWindow", "pdf文件"))
        self.label.setText(_translate("pdf_mark_create_MainWindow", "tolerance:"))
        self.tolerance_lineEdit.setText(_translate("pdf_mark_create_MainWindow", "0"))
        self.clear_table_pushButton.setText(_translate("pdf_mark_create_MainWindow", "清除全部"))
        self.start_pushButton.setText(_translate("pdf_mark_create_MainWindow", "开始"))
        self.menuHelp.setTitle(_translate("pdf_mark_create_MainWindow", "Help"))
        self.help_action.setText(_translate("pdf_mark_create_MainWindow", "Help Document"))
